backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "content"
    label: "Inhalte"
    files:
      - label: "Navbar Main"
        name: "navbarMain"
        file: "public/content.json"
        fields:
          - label: "Navbar Items"
            name: "itemData"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Section ID"
                name: "sectionId"
                widget: "string"

      - label: "Main Section"
        name: "mainSection"
        file: "public/content.json"
        fields:
          - label: "Banner Items"
            name: "bannerItemData"
            widget: "list"
            fields:
              - label: "Content"
                name: "content"
                widget: "string"

      - label: "Service Section"
        name: "serviceSection"
        file: "public/content.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Service Items"
            name: "itemData"
            widget: "list"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"

      - label: "Image Gallery"
        name: "imgGallery"
        file: "public/content.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Gallery Images"
            name: "galleryImgData"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"

      - label: "Contact Section"
        name: "contactSection"
        file: "public/content.json"
        fields:
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Enable Captcha"
                name: "enableCaptcha"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "list"
                    field:
                      - label: "Text"
                        name: "text"
                        widget: "string"
                  - label: "Button"
                    name: "button"
                    widget: "string"
              - label: "Verification"
                name: "verification"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "list"
                    field:
                      - label: "Text"
                        name: "text"
                        widget: "string"
              - label: "Info Data"
                name: "infoData"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "list"
                    field:
                      - label: "Text"
                        name: "text"
                        widget: "string"
                  - label: "Info Options"
                    name: "infoOptions"
                    widget: "list"
                    field:
                      - label: "Option"
                        name: "option"
                        widget: "string"
                  - label: "Email"
                    name: "email"
                    widget: "string"
          - label: "Captcha"
            name: "captcha"
            widget: "object"
            fields:
              - label: "Phrases"
                name: "phrases"
                widget: "list"
                field:
                  - label: "Phrase"
                    name: "phrase"
                    widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"

      - label: "Knowledge Section"
        name: "knowledgeSection"
        file: "public/content.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Knowledge Data"
            name: "knowledgeData"
            widget: "list"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Teaser"
                name: "teaser"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"

      - label: "Footer"
        name: "footer"
        file: "public/content.json"
        fields:
          - label: "Footer Items"
            name: "itemData"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"

      - label: "Popups"
        name: "popups"
        file: "public/content.json"
        fields:
          - label: "Contact Popup"
            name: "contact"
            widget: "object"
            fields:
              - label: "Content"
                name: "content"
                widget: "list"
                field:
                  - label: "Text"
                    name: "text"
                    widget: "string"
              - label: "Button 1"
                name: "button1"
                widget: "string"
              - label: "Button 2"
                name: "button2"
                widget: "string"
          - label: "Privacy Popup"
            name: "privacy"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
