backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "content"
    label: "Content"
    files:
      - label: "Navbar"
        name: "navbar"
        file: "public/content.json"
        fields:
          - label: "Navbar Items"
            name: "navbarMain.itemData"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Section ID"
                name: "sectionId"
                widget: "string"
