backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "content"
    label: "Content"
    files:
      - label: "Navbar"
        name: "navbar"
        file: "public/content.json"
        fields:
          - label: "Navbar Items"
            name: "navbarMain"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Section ID"
                name: "sectionId"
                widget: "string"
          - label: "Banner Items"
            name: "bannerItemData"
            widget: "list"
            fields:
              - label: "Kern Kompetenz"
                name: "content"
                widget: "string"
  - name: "test"
    label: "TEST"
    files:
      - label: "Service"
        name: "service"
        file: "public/content.json"
        fields:
          - label: "Service Items"
            name: "serviceItemData"
            widget: "list"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
