# local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - label: "Navigation"
    name: "navbar"
    description: >
      In diesem Bereich, können die Texte der Navigationsleiste angepasst werden, welche sich am oberen Bildschirmrand befindet.
    files:
      - label: "Navigation anzeigen und bearbeiten"
        name: "navbarItems"
        file: "public/content.json"
        fields:
          - label: "Navbar Item Titel"
            name: "navbarMain"
            allow_add: false
            widget: "list"
            fields:
              - label: "Text für Navigations Menüpunkt"
                name: "title"
                widget: "string"

  - label: "Kompetenzen Startseite"
    name: "banner"
    description: >
      Auf der Startseite befinden sich aktuell 3 Kernkompetenzen unterhalb des Logos. Diese können hier eingesehen und angepasst werden.
    files:
      - label: "Kompetenzen anzeigen und bearbeiten"
        name: "bannerItems"
        file: "public/content.json"
        fields:
          - label: "Banner Item Data"
            name: "bannerItemData"
            allow_add: false
            widget: "list"
            fields:
              - label: "Beschreibung für Kernkompetenz"
                name: "content"
                widget: "string"

  - label: "Service & Dienstleistung"
    name: "service"
    description: >
      In diesem Abschnitt können die Überschriften und Inhaltstexte zur Beschreibung der Dienstleistungen angepasst werden. Es ist auch möglich neue Inhalte mit auf zu nehmen. Bilder werden aktuell in Dummy form Automatisch über das Backend eingepflegt.
    files:
      - label: "Services & Dienstleistungen anzeigen und bearbeiten"
        name: "serviceItems"
        file: "public/content.json"
        fields:
          - label: "Service Item Data"
            name: "serviceItemData"
            allow_add: true
            widget: "list"
            fields:
              - label: "Überschrift / Titel der Dienstleistung"
                name: "header"
                widget: "string"
              - label: "Beschreibung der Dienstleistung"
                name: "description"
                widget: "text"

  - label: "Gallerie Bilder Texte"
    name: "gallery"
    description: >
      Zur Anpassung der Bildbeschreibungen kann dieser Bereich verwendet werden. Aktuell ist es nur vorgesehen Titel und Beschreibung zu editieren. Die Bilder werden zu einem späteren Zeitpunkt verknüpft.
      WICHTIG: BITTE KEINE EINTRÄGE LÖSCHEN, DA AKTUELL DIE ARTIKELANZAHL BESTIMMT WIEVIELE BILDER ANGEZEIGT WERDEN! BITTE VORHER UM RÜCKSPRACHE FÜR ÄNDERUNGEN!
    files:
      - label: "Texte der Bilder anzeigen und bearbeiten"
        name: "galleryImg"
        file: "public/content.json"
        fields:
          - label: "Gallery Img Data"
            name: "galleryImgData"
            allow_add: true
            widget: "list"
            fields:
              - label: "Bildüberschrift / Beschreibung"
                name: "title"
                widget: "string"
              - label: "Kurze Erläuterung was auf dem Bild zu sehen ist"
                name: "description"
                required: false
                widget: "text"

  - label: "Kontakt & Captcha"
    name: "contact"
    description: >
      Zur Anpassung der Beschreibungstexte zur Kontaktaufnahme, zur Anpassung der Erklärung des Captchas und zur Änderung der Kontaktinformationen ist dieser Bereich vorgesehen. Er ist in drei Gruppen gegliedert. Kontaktaufnahme, Captcha Abfrage, Infos die angzeigt werden.
    files:
      - label: "Kontaktdaten & Beschreibungstexte anzeigen und bearbeiten"
        name: "contactData"
        file: "public/content.json"
        allow_add: false
        widget: "list"
        fields:
          - label: "Kontaktaufnahme - Captcha triggern"
            name: "enableCaptcha"
            allow_add: false
            widget: "list"
            fields:
              - label: "Überschrift Innerhalb des Kontaktblocks"
                name: "header"
                widget: "string"
              - label: "Erläuterung der weiteren Schritte / Teaser"
                name: "descriptions"
                allow_add: false
                widget: "list"
                fields:
                  - { label: Beschreibung, name: description, widget: string }
              - label: "Text der Schaltfläche, um Captcha zu aktivieren"
                name: "button"
                widget: "string"
              - label: "Lösungshinweis für angezeigtes Wort"
                name: "captchaDescription"
                widget: "string"

          - label: "Verifizierung erforderlich"
            name: "verification"
            allow_add: false
            widget: "list"
            fields:
              - label: "Überschrift Innerhalb des Kontaktblocks"
                name: "header"
                widget: "string"
              - label: "Beschreibung Aufgabe und Lösung"
                name: "descriptions"
                allow_add: false
                widget: "list"
                fields:
                  - { label: Beschreibung, name: description, widget: string }

          - label: "Kontaktdaten und Weiterführende Informationen"
            name: "contactData"
            allow_add: false
            widget: "list"
            fields:
              - label: "Überschrift Innerhalb des Kontaktblocks"
                name: "header"
                widget: "string"
              - label: "Kurze Einleitung und aufforderung zur Mitwirkung"
                name: "descriptions"
                allow_add: false
                widget: "list"
                fields:
                  - { label: Beschreibung, name: description, widget: string }
              - label: "Aufzählung von Nützlichen Informationen"
                name: "infoOptions"
                allow_add: false
                widget: "list"
                fields:
                  - { label: Info Beschreibung, name: option, widget: string }
              - label: "angzeigte Email adresse"
                name: "email"
                widgeht: "string"

  - label: "Wissensdatenbank"
    name: "knowledgeBase"
    description: >
      Hier können die Wendekacheln im letzten Abschnitt der Seite bearbeitet werden.
    files:
      - label: "Wissensartikel anzeigen und bearbeiten"
        name: "knowledgeData"
        file: "public/content.json"
        allow_add: false
        widget: "list"
        fields:
          - label: "Aktuell vorhandene Artikel"
            name: "knowledgeData"
            allow_add: true
            widget: "list"
            fields:
              - { label: Teaser auf Vorderseite, name: teaser, widget: string }
              - { label: Überschrift Rückseite, name: header, widget: string }
              - {
                  label: Beschreibung auf Rückseite,
                  name: description,
                  widget: text,
                }

  - label: "Footer"
    name: "footer"
    description: >
      Hier können die Eintragungen in der Fußzeile angepasst und ergänzt werden.
    files:
      - label: "Fußzeile anzeigen und bearbeiten"
        name: "footerItemData"
        file: "public/content.json"
        allow_add: false
        widget: "list"
        fields:
          - label: "Footer Navigationselemente"
            name: "footerItemData"
            allow_add: true
            widget: "list"
            fields:
              - { label: Beschreibung, name: title, widget: string }
              - { label: Url, name: url, widget: string }

  - label: "Popups"
    name: "popups"
    description: >
      Alle vorhandenen Popups auf der Seite können hier bearbeitet werden. Dies gilt beispielsweise für den Datenschutz- / Cookie hinweis beim ersten Besuch der Seite, sowie der Info zur Kontaktaufnahme.
    files:
      - label: "Popups anzeigen und bearbeiten"
        name: "popups"
        file: "public/content.json"
        fields:
          - label: "Popup Zur Kontaktaufnahme"
            name: "popupContact"
            allow_add: false
            widget: "list"
            fields:
              - label: "1. Schalfläche Beschreibung"
                name: "button1"
                widget: "string"
              - label: "2. Schalfläche Beschreibung"
                name: "button2"
                widget: "string"
              - label: "Inhalt / Fragen im Popupfenster"
                name: "content"
                widget: "list"
                fields:
                  - { label: Text, name: text, widget: string }

          - label: "Popup Datenschutz & Cookies"
            name: "popupPrivacy"
            allow_add: false
            widget: "list"
            fields:
              - label: "Überschrift"
                name: "header"
                widget: "string"
              - label: "Schaltfläche zur Bestätigung"
                name: "button"
                widget: "string"

  - label: "Überschriften"
    name: "sectionHeaders"
    description: >
      Die Seite ist in mehrere Sektionen aufgeteilt und jede Sektion trägt eine Überschrift. Diese Überschriften können hier für jede Sektion angepasst werden.
    files:
      - label: "Überschriften anzeigen und bearbeiten"
        name: "sectionHeaders"
        file: "public/content.json"
        allow_add: false
        fields:
          - label: "Überschriften"
            name: "sectionHeaders"
            widget: "list"
            fields:
              - label: "Service Section Header"
                name: "serviceSectionHeader"
                widget: "string"
              - label: "Img Gallery Header"
                name: "imgGalleryHeader"
                widget: "string"
              - label: "Contact Section Header"
                name: "contactSectionHeader"
                widget: "string"
              - label: "Knowledge Section Header"
                name: "knowledgeSectionHeader"
                widget: "string"
